### PR TITLE
ci.appveyor

### PR DESCRIPTION
**Pull request by edewit**
add ci with appveyor

### CODE REVIEW

**Comment by edewit** [comment]
@matzew ci for .net projects free for opensource what do you think?

**Comment by matzew** [comment]
sure!

can we hook to it from GH ?

**Comment by edewit** [comment]
Yeah it will monitor gh and build when there are changes

**Comment by matzew** [comment]
how to enable? service hooks?

On Friday, March 27, 2015, Erik Jan de Wit notifications@github.com wrote:

> Yeah it will monitor gh and build when there are changes
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/aerogear/aerogear-unifiedpush-dotnet-client/pull/3#issuecomment-86896121
> .

## 

Sent from Gmail Mobile

**Pull request merged**
